### PR TITLE
fix: turn off accessibility for screen and header beneath transparent modal on Android

### LINKED ISSUE #1204: Android screen reader is able to interact with content beneath `transparentModal` and `containedTransparentModal` stack
## Description

When a screen is stacked on top of another using the `transparentModal` or `containedTransparentModal` presentation type, Android screen reader TalkBack is still able to read and interact with the content of the screen underneath even though it's not visible.

### Screenshots

https://user-images.githubusercontent.com/456562/140495081-b8f4ad0a-e89a-4841-8617-8d3f256466de.mp4

## Steps To Reproduce

1. Install [Android Accessibility Suite](https://play.google.com/store/apps/details?id=com.google.android.marvin.talkback) to an Android device.
2. Run this project's [example app](https://github.com/software-mansion/react-native-screens/tree/master/Example) on the device.
3. [Turn on TalkBack](https://support.google.com/accessibility/android/answer/6007100).
4. In the example app, open the `containedTransparentModal` example modal.
5. Tap within the modal area.

### Expected behavior

Only the modal content is read by TalkBack.

### Actual behavior

TalkBack can read and interact with other example buttons underneath the modal.

## Reproduction

The issue is reproducible from the example app from this repository: https://github.com/software-mansion/react-native-screens/tree/master/Example.

## Platform

- [ ] iOS
- [x] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [ ] Managed workflow
- [x] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |   0.66.0     |
| @react-navigation/native               |     5.9.2    |
| react-native-screens                   |     3.9.0    |

### PR DESCRIPTION
**Pull request by kacperkapusciak**
## Description

This PR turns off accessibility for screen and header beneath transparent modal on Android.

Fixes #1204

## Changes

Added a `turnOffA11yUnderTransparentScreen` method invoked in ScreenStack's `onUpdate` method. It iterates through the stack to search for the first transparent screen from the top and turns off a11y for the screen and header beneath.

### Before

https://user-images.githubusercontent.com/39658211/140723838-90dec12d-5d3b-4235-80d5-b456a28d7551.mp4

### After

https://user-images.githubusercontent.com/39658211/140723856-53a1057e-77cf-43b5-ac7c-4b34632df53c.mp4

## Test code and steps to reproduce

`Test1204.tsx` in `TestsExample/` project

## Checklist

- [x] Included code example that can be used to test this change
- [ ] Ensured that CI passes

### CODE REVIEW

File: android/src/main/java/com/swmansion/rnscreens/ScreenStack.kt [hunk 1]
```diff
@@ -236,10 +236,26 @@ class ScreenStack(context: Context?) : ScreenContainer<ScreenStackFragment>(cont
...
+        if (mScreenFragments.size > 1) {
+            mTopScreen?.let {
+                if (isTransparent(it)) {
+                    val belowTop = mScreenFragments[mScreenFragments.lastIndex - 1].screen
+                    belowTop.changeAccessibilityMode(IMPORTANT_FOR_ACCESSIBILITY_NO_HIDE_DESCENDANTS)
+                }
+            }
+        }
+
+        topScreen?.changeAccessibilityMode(IMPORTANT_FOR_ACCESSIBILITY_AUTO)
```
Comment (WoLewicki) [inline android/src/main/java/com/swmansion/rnscreens/ScreenStack.kt:256]: Is this option set on all of the children when setting it on the `Screen`? If so, what if the user had different accessibility mode set on one of the children? Wouldn't we override it here?

Comment (kacperkapusciak) [reply android/src/main/java/com/swmansion/rnscreens/ScreenStack.kt:258]: It is correctly handled by the `auto` setting. I've added a test for that in 078c69c to check this.
