### PR TITLE
fix(Android): center headerTitleAlign below Android API 29

### LINKED ISSUE #2435: headerTitleAlign set to "center" is broken on Android 4.0.0-beta.14
### Description

Hi,

I am using react-native-screens 4.0.0-beta.14 and I would like to center my title, can be always reproduced within the example of this repo:

https://github.com/user-attachments/assets/36cf5cab-6845-4b52-a671-392ec9c326a9

### Steps to reproduce

Either have a Navigation with headerTitleAlign set to center or clone my fork, run the example app, and follow the video

### Snack or a link to a repository

https://github.com/itsramiel/react-native-screens/tree/chore/reproduce

### Screens version

4.0.0-beta.14

### React Native version

0.74.5

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

_No response_

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by alduzy**
## Description

This PR intents to fix `headerTitleAlign: 'center'` breaking layout on android API <= 29.

I found changes added in https://github.com/software-mansion/react-native-screens/pull/2332, which fixed a related toolbar problem on android API <= 29, affect the correct layout of the centered title.

The `EXACTLY` [MeasureSpec](https://developer.android.com/reference/android/view/View.MeasureSpec) causes the title not to obtain as much space as it needs. Fortunately changing the spec to `AT_MOST` in the custom `layoutCallback` fixes the issue without introducing regression.

I also included a check for the current `softInputMode` to abandon the action if it is not set to `adjustPan`.

Fixes #2435 

## Changes

- updated `Test2332.tsx` repro
- changed measureSpec used in `layoutCallback`
- added `softInputMode` check

## Screenshots / GIFs

| Before https://github.com/software-mansion/react-native-screens/pull/2332 | Before | After |
| --- | --- | --- |
|  Screenshot_20241024_114026 | Screenshot_20241024_113943 | Screenshot_20241024_113853 |

## Test code and steps to reproduce

- use `Test2332.tsx` repro

## Checklist

- [x] Included code example that can be used to test this change
- [x] Ensured that CI passes

### CODE REVIEW

File: android/src/main/java/com/swmansion/rnscreens/CustomToolbar.kt [hunk 1]
```diff
@@ -19,16 +21,22 @@ open class CustomToolbar(
             override fun doFrame(frameTimeNanos: Long) {
                 isLayoutEnqueued = false
                 measure(
-                    MeasureSpec.makeMeasureSpec(width, MeasureSpec.EXACTLY),
-                    MeasureSpec.makeMeasureSpec(height, MeasureSpec.EXACTLY),
+                    MeasureSpec.makeMeasureSpec(width, MeasureSpec.AT_MOST),
+                    MeasureSpec.makeMeasureSpec(height, MeasureSpec.AT_MOST),
```
Comment (kkafar) [inline android/src/main/java/com/swmansion/rnscreens/CustomToolbar.kt:25]: 1. This is fine as long as it does not break any other behaviour. Please check header behaviours carefully, especially on newer Android API levels (34, 35).

2. Please add a comment here why this is done. 
3. Maybe we should select the measure spec depending on the API level being in use? So that we're sure we do not change the behaviour for newer API levels?

File: android/src/main/java/com/swmansion/rnscreens/CustomToolbar.kt [hunk 2]
```diff
@@ -19,16 +21,22 @@ open class CustomToolbar(
...
     override fun requestLayout() {
         super.requestLayout()
-        if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.Q) {
+        val softInputMode =
+            (context as ThemedReactContext)
+                .currentActivity
+                ?.window
+                ?.attributes
+                ?.softInputMode
+        if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.Q && softInputMode == WindowManager.LayoutParams.SOFT_INPUT_ADJUST_PAN) {
```
Comment (kkafar) [inline android/src/main/java/com/swmansion/rnscreens/CustomToolbar.kt:39]: I like introduction of this check, however I need you to confirm that issue from #2332 is not reintroduced.

**Review by kkafar — CHANGES_REQUESTED** [review]

File: android/src/main/java/com/swmansion/rnscreens/CustomToolbar.kt (hunk 2 above)
Comment (alduzy) [reply android/src/main/java/com/swmansion/rnscreens/CustomToolbar.kt:39]: From what I've tested the issue mentioned only appeared when mode was set to `adjustPan`. I am not 100% certain though. @tboba Do you remember if it was an issue with other modes?

Comment (kkafar) [reply android/src/main/java/com/swmansion/rnscreens/CustomToolbar.kt:39]: I was involved in fixing it & can confirm that it occurred only for `adjustPan`.

However have you tested that? You do set this in `AndroidManifest` file of the application under the `softInputMode` key (or something similar).

File: android/src/main/java/com/swmansion/rnscreens/CustomToolbar.kt (hunk 1 above)
Comment (alduzy) [reply android/src/main/java/com/swmansion/rnscreens/CustomToolbar.kt:25]: @kkafar I believe this layoutCallback is not triggered in any other circumstances. It is called conditionally when API <= 29 and softInputMode is set to "adjustPan" in the modified `requestLayout` in the same file. Thus I don't think we need to add conditions/comment here.

File: android/src/main/java/com/swmansion/rnscreens/CustomToolbar.kt (hunk 2 above)
Comment (alduzy) [reply android/src/main/java/com/swmansion/rnscreens/CustomToolbar.kt:39]: I have tested it and didn't found any problems with softInputModes other than `adjustPan`, which is handled by this check.

File: android/src/main/java/com/swmansion/rnscreens/CustomToolbar.kt (hunk 1 above)
Comment (kkafar) [reply android/src/main/java/com/swmansion/rnscreens/CustomToolbar.kt:25]: Yes, I think you're right. I wrote this code but I've forgotten about it.

**Review by kkafar — APPROVED** [review]
Thanks for answering my concerns. I think we look good, beside one thing:

I'll insist you add a comment shortly explaining that these measure specs are selected to work for Android APIs level <= 29. 

Other than that - 🟢
