### PR TITLE
fix(Android): fix build deprecations

### LINKED ISSUE #2018: Many "Deprecated in Java" and other warnings when building for Android.
### Description

There are many "Deprecated in Java" warnings and other warnings when building for Android:

```
> Task :react-native-screens:processDebugManifest
package="com.swmansion.rnscreens" found in source AndroidManifest.xml: C:\Users\
Jack\Documents\ScreensDeprecatedWarnings\node_modules\react-native-screens\andro
id\src\main\AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xm
l is no longer supported, and the value is ignored.
Recommendation: remove package="com.swmansion.rnscreens" from the source Android
Manifest.xml: C:\Users\Jack\Documents\ScreensDeprecatedWarnings\node_modules\rea
ct-native-screens\android\src\main\AndroidManifest.xml.

> Task :react-native-screens:compileDebugKotlin
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenContainerView
Manager.kt:5:46 'ReactModule' is deprecated. Deprecated in Java
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenContainerView
Manager.kt:10:2 'ReactModule' is deprecated. Deprecated in Java
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment
.kt:65:28 'setter for targetElevation: Float' is deprecated. Deprecated in Java
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment
.kt:128:28 'setter for targetElevation: Float' is deprecated. Deprecated in Jav
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderCo
nfig.kt:86:34 'getter for systemWindowInsetTop: Int' is deprecated. Deprecated i
n Java
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderCo
nfig.kt:229:37 'setColorFilter(Int, PorterDuff.Mode): Unit' is deprecated. Depre
cated in Java
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderCo
nfigViewManager.kt:7:46 'ReactModule' is deprecated. Deprecated in Java
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderCo
nfigViewManager.kt:18:2 'ReactModule' is deprecated. Deprecated in Java
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderSu
bviewManager.kt:4:46 'ReactModule' is deprecated. Deprecated in Java
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderSu
bviewManager.kt:12:2 'ReactModule' is deprecated. Deprecated in Java
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStackViewMana
ger.kt:6:46 'ReactModule' is deprecated. Deprecated in Java
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStackViewMana
ger.kt:15:2 'ReactModule' is deprecated. Deprecated in Java
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.k
t:6:46 'ReactModule' is deprecated. Deprecated in Java
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.k
t:24:2 'ReactModule' is deprecated. Deprecated in Java
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenViewManager.k
t:47:42 'setStateWrapper(StateWrapper!): Unit' is deprecated. Deprecated in Java
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.
kt:137:47 'replaceSystemWindowInsets(Int, Int, Int, Int): WindowInsetsCompat' is
 deprecated. Deprecated in Java
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.
kt:138:51 'getter for systemWindowInsetLeft: Int' is deprecated. Deprecated in J
ava
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.
kt:140:51 'getter for systemWindowInsetRight: Int' is deprecated. Deprecated in
Java
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.
kt:141:51 'getter for systemWindowInsetBottom: Int' is deprecated. Deprecated in
 Java
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/main/java/com/swmansion/rnscreens/SearchBarManager.kt
:6:46 'ReactModule' is deprecated. Deprecated in Java
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/main/java/com/swmansion/rnscreens/SearchBarManager.kt
:17:2 'ReactModule' is deprecated. Deprecated in Java
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/main/java/com/swmansion/rnscreens/SearchBarManager.kt
:100:22 Parameter 'view' is never used
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/main/java/com/swmansion/rnscreens/SearchBarManager.kt
:100:43 Parameter 'placeholder' is never used
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/main/java/com/swmansion/rnscreens/SearchBarView.kt:14
7:43 Parameter 'flag' is never used
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/main/java/com/swmansion/rnscreens/events/HeaderHeight
ChangeEvent.kt:5:44 'RCTEventEmitter' is deprecated. Deprecated in Java
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/main/java/com/swmansion/rnscreens/events/HeaderHeight
ChangeEvent.kt:10:5 'constructor Event<T : Event<(raw) Event<*>>!>(Int)' is depr
ecated. Deprecated in Java
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/main/java/com/swmansion/rnscreens/events/HeaderHeight
ChangeEvent.kt:17:44 'RCTEventEmitter' is deprecated. Deprecated in Java
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/main/java/com/swmansion/rnscreens/events/HeaderHeight
ChangeEvent.kt:20:25 'receiveEvent(Int, String!, WritableMap?): Unit' is depreca
ted. Deprecated in Java
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/paper/java/com/swmansion/rnscreens/FabricEnabledViewG
roup.kt:5:37 'FabricViewStateManager' is deprecated. Deprecated in Java
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/paper/java/com/swmansion/rnscreens/FabricEnabledViewG
roup.kt:9:48 'FabricViewStateManager' is deprecated. Deprecated in Java
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/paper/java/com/swmansion/rnscreens/FabricEnabledViewG
roup.kt:11:42 Parameter 'width' is never used
w: file:///C:/Users/Jack/Documents/ScreensDeprecatedWarnings/node_modules/react-
native-screens/android/src/paper/java/com/swmansion/rnscreens/FabricEnabledViewG
roup.kt:11:54 Parameter 'height' is never used
```

### Steps to reproduce

1. Run to get the latest virgin react-native npx react-native init ScreensDeprecatedWarnings
2. Run npm install react-native-screens
3. Run npm run android

### Snack or a link to a repository

https://github.com/jacksonlevine/ScreensDeprecatedWarnings

### Screens version

3.29.0

### React Native version

0.73.0

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Moto G4

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by alduzy**
## Description

This PR intents to fix some "Deprecated in Java" warnings when building on android. I decided not to suppress warnings manually when it is inescapable to avoid the warning.

Fixes #2018 

## Changes

- replaced deprecated targetElavation with elevation
- adjusted usage of porter duff color filter
- calculating header top inset using recent method if android API >= 30 (the warning persists as the previous APIs still require deprecated method)
- fixed guarded runnable deprecated warning
- removed unused import

### Before

```
> Task :react-native-screens:compileDebugKotlin
'compileDebugJavaWithJavac' task (current target is 11) and 'compileDebugKotlin' task (current target is 17) jvm target compatibility should be set to the same Java version.
Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain

w: file:///Users/alexduzy/Projects/react-native-screens/Example/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/Screen.kt:83:22 'constructor GuardedRunnable(ReactContext!)' is deprecated. Deprecated in Java
w: file:///Users/alexduzy/Projects/react-native-screens/Example/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt:65:27 'setter for targetElevation: Float' is deprecated. Deprecated in Java
w: file:///Users/alexduzy/Projects/react-native-screens/Example/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt:128:27 'setter for targetElevation: Float' is deprecated. Deprecated in Java
w: file:///Users/alexduzy/Projects/react-native-screens/Example/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.kt:86:34 'getter for systemWindowInsetTop: Int' is deprecated. Deprecated in Java
w: file:///Users/alexduzy/Projects/react-native-screens/Example/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.kt:231:37 'setColorFilter(Int, PorterDuff.Mode): Unit' is deprecated. Deprecated in Java
w: file:///Users/alexduzy/Projects/react-native-screens/Example/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.kt:63:22 'constructor GuardedRunnable(ReactContext!)' is deprecated. Deprecated in Java
w: file:///Users/alexduzy/Projects/react-native-screens/Example/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.kt:108:22 'constructor GuardedRunnable(ReactContext!)' is deprecated. Deprecated in Java
w: file:///Users/alexduzy/Projects/react-native-screens/Example/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.kt:135:47 'replaceSystemWindowInsets(Int, Int, Int, Int): WindowInsetsCompat' is deprecated. Deprecated in Java
w: file:///Users/alexduzy/Projects/react-native-screens/Example/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.kt:136:51 'getter for systemWindowInsetLeft: Int' is deprecated. Deprecated in Java
w: file:///Users/alexduzy/Projects/react-native-screens/Example/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.kt:138:51 'getter for systemWindowInsetRight: Int' is deprecated. Deprecated in Java
w: file:///Users/alexduzy/Projects/react-native-screens/Example/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.kt:139:51 'getter for systemWindowInsetBottom: Int' is deprecated. Deprecated in Java
w: file:///Users/alexduzy/Projects/react-native-screens/Example/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/SearchBarManager.kt:100:22 Parameter 'view' is never used
w: file:///Users/alexduzy/Projects/react-native-screens/Example/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/SearchBarManager.kt:100:43 Parameter 'placeholder' is never used
w: file:///Users/alexduzy/Projects/react-native-screens/Example/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/SearchBarView.kt:147:43 Parameter 'flag' is never used
w: file:///Users/alexduzy/Projects/react-native-screens/Example/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/events/HeaderHeightChangeEvent.kt:6:44 'RCTEventEmitter' is deprecated. Deprecated in Java
w: file:///Users/alexduzy/Projects/react-native-screens/Example/node_modules/react-native-screens/android/src/paper/java/com/swmansion/rnscreens/FabricEnabledViewGroup.kt:11:42 Parameter 'width' is never used
w: file:///Users/alexduzy/Projects/react-native-screens/Example/node_modules/react-native-screens/android/src/paper/java/com/swmansion/rnscreens/FabricEnabledViewGroup.kt:11:54 Parameter 'height' is never used
w: file:///Users/alexduzy/Projects/react-native-screens/Example/node_modules/react-native-screens/android/src/paper/java/com/swmansion/rnscreens/FabricEnabledViewGroup.kt:11:67 Parameter 'headerHeight' is never used
```

### After

```
> Task :react-native-screens:compileDebugKotlin
'compileDebugJavaWithJavac' task (current target is 11) and 'compileDebugKotlin' task (current target is 17) jvm target compatibility should be set to the same Java version.
Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain

w: file:///Users/alexduzy/Projects/react-native-screens/Example/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.kt:90:34 'getter for systemWindowInsetTop: Int' is deprecated. Deprecated in Java
w: file:///Users/alexduzy/Projects/react-native-screens/Example/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.kt:135:47 'replaceSystemWindowInsets(Int, Int, Int, Int): WindowInsetsCompat' is deprecated. Deprecated in Java
w: file:///Users/alexduzy/Projects/react-native-screens/Example/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.kt:136:51 'getter for systemWindowInsetLeft: Int' is deprecated. Deprecated in Java
w: file:///Users/alexduzy/Projects/react-native-screens/Example/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.kt:138:51 'getter for systemWindowInsetRight: Int' is deprecated. Deprecated in Java
w: file:///Users/alexduzy/Projects/react-native-screens/Example/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/ScreenWindowTraits.kt:139:51 'getter for systemWindowInsetBottom: Int' is deprecated. Deprecated in Java
w: file:///Users/alexduzy/Projects/react-native-screens/Example/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/SearchBarManager.kt:100:22 Parameter 'view' is never used
w: file:///Users/alexduzy/Projects/react-native-screens/Example/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/SearchBarManager.kt:100:43 Parameter 'placeholder' is never used
w: file:///Users/alexduzy/Projects/react-native-screens/Example/node_modules/react-native-screens/android/src/main/java/com/swmansion/rnscreens/SearchBarView.kt:147:43 Parameter 'flag' is never used
w: file:///Users/alexduzy/Projects/react-native-screens/Example/node_modules/react-native-screens/android/src/paper/java/com/swmansion/rnscreens/FabricEnabledViewGroup.kt:11:42 Parameter 'width' is never used
w: file:///Users/alexduzy/Projects/react-native-screens/Example/node_modules/react-native-screens/android/src/paper/java/com/swmansion/rnscreens/FabricEnabledViewGroup.kt:11:54 Parameter 'height' is never used
w: file:///Users/alexduzy/Projects/react-native-screens/Example/node_modules/react-native-screens/android/src/paper/java/com/swmansion/rnscreens/FabricEnabledViewGroup.kt:11:67 Parameter 'headerHeight' is never used
```

## Test code and steps to reproduce

- build android app to compare deprecation warnings quantity
- run the example app and see wether the header shadow, backButton color and top inset behave correctly

## Checklist

- [ ] Ensured that CI passes

### CODE REVIEW

File: android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt [hunk 1]
```diff
@@ -62,7 +62,8 @@ class ScreenStackFragment : ScreenFragment, ScreenStackFragmentWrapper {
 
     override fun setToolbarShadowHidden(hidden: Boolean) {
         if (isToolbarShadowHidden != hidden) {
-            appBarLayout?.targetElevation = if (hidden) 0f else PixelUtil.toPixelFromDIP(4f)
+            appBarLayout?.elevation = if (hidden) 0f else PixelUtil.toPixelFromDIP(4f)
+            appBarLayout?.stateListAnimator = null
```
Comment (kkafar) [inline android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt:66]: Why `null` here, instead of leaving default?

**Review by kkafar — COMMENTED** [review]
Just a single question, rest of the changes seems perfectly fine 🟢

File: android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt (hunk 1 above)
Comment (alduzy) [reply android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt:66]: Without it the elevation is not setting properly on initial render, I suppose the shadow is there by default so we have to reset it.

File: android/src/main/java/com/swmansion/rnscreens/Screen.kt [hunk 2]
```diff
@@ -80,7 +80,7 @@ class Screen(context: ReactContext?) : FabricEnabledViewGroup(context) {
     private fun updateScreenSizePaper(width: Int, height: Int) {
         val reactContext = context as ReactContext
         reactContext.runOnNativeModulesQueueThread(
-            object : GuardedRunnable(reactContext) {
+            object : GuardedRunnable(reactContext.exceptionHandler) {
```
Comment (kkafar) [inline android/src/main/java/com/swmansion/rnscreens/Screen.kt:83]: I saw the warning you pasted in PR description, but I checked in [source code](https://github.com/facebook/react-native/blob/362abb9ffea5af7e6e5616849fbce28166c758a0/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/GuardedRunnable.java#L18-L24) & this is not deprecated 🤷🏻‍♂️  

It's fine I guess

File: android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt (hunk 1 above)
Comment (kkafar) [reply android/src/main/java/com/swmansion/rnscreens/ScreenStackFragment.kt:66]: Ok

**Review by kkafar — APPROVED** [review]
I think we can merge 🟢 Thank you!

File: android/src/main/java/com/swmansion/rnscreens/Screen.kt (hunk 2 above)
Comment (tboba) [reply android/src/main/java/com/swmansion/rnscreens/Screen.kt:83]: That's actually quite weird - according to the source code from Android Studio, GuardedRunnable with constructor with `ReactContext` parameter is deprecated though - I'm concerned why there's any difference here 🤔 

image

File: android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.kt [hunk 3]
```diff
@@ -82,7 +84,9 @@ class ScreenStackHeaderConfig(context: Context) : ViewGroup(context) {
         // we want to save the top inset before the status bar can be hidden, which would resolve in
         // inset being 0
         if (headerTopInset == null) {
-            headerTopInset = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M)
+            headerTopInset = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R)
```
Comment (tboba) [inline android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.kt:87]: Do you know if `VERSION_CODES.R` is already defined on lower supported Android versions?

**Review by tboba — APPROVED** [review]
LGTM! Just a small note from me :smile:

File: android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.kt (hunk 3 above)
Comment (alduzy) [reply android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.kt:87]: I don't think it is, but it should be converted to a number during build time so it does not matter according to this thread: https://stackoverflow.com/questions/21874227/why-do-android-os-build-version-codes-work-on-older-platforms

Comment (kkafar) [reply android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.kt:87]: Yeah, but where does the guarantee that this symbol is available in build time comes from?

Comment (kkafar) [reply android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.kt:87]: We have this guarantee only since August 2023.

I'm leaving link here for future git-blaming activities.

Comment (kkafar) [reply android/src/main/java/com/swmansion/rnscreens/ScreenStackHeaderConfig.kt:87]: Actually we don't have this guarantee, cause this link is about `target`. I guess we can reasonably safely assume that `target` & `compile` point to the same version 🤷🏻

File: android/src/main/java/com/swmansion/rnscreens/Screen.kt (hunk 2 above)
Comment (alduzy) [reply android/src/main/java/com/swmansion/rnscreens/Screen.kt:83]: I've found similar fix here: https://github.com/software-mansion/react-native-reanimated/pull/1031

Comment (tboba) [reply android/src/main/java/com/swmansion/rnscreens/Screen.kt:83]: The reason why it is not deprecated right now is that since 0.73 this constructor has been de-deprecated 😄 
I can see on [0.72](https://github.com/facebook/react-native/blob/0.72-stable/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/GuardedRunnable.java) that `@Deprecated` is still there and has been removed since [this](https://github.com/facebook/react-native/commit/330639f74018cfeda28e74c6dae8110d97603860) commit.

**Comment by tboba** [comment]
Just one question about warnings @kkafar @alduzy - currently, some warnings about unused parameters are popping up while building screens. Do you think we should suppress them with annotation?

**Comment by kkafar** [comment]
I think they're popping because `FabricEnabledViewGroup` is used only as a stub while running on paper -> thus it is indeed unused but must be present. It is safe & ok to supress them with annotation
