### PR TITLE
fix(Android): screen goes blank when going back on fabric

### LINKED ISSUE #1685: When I want to go to the previous page, everything suddenly disappears
### Description

I'm opening a new page on Android and everything is fine. When I want to come back from that opened page, all Views and Texts disappear from the screen. A white screen appears. Then my back page opens.

At this stage, I want the objects on my screen not to disappear.

In my opinion such a problem occurs when **FABRIC is enabled**. If fabric is not enabled, everything continues as normal. Could it be that the react-navigation package's fabric support is not working properly?

Here is the video.

https://user-images.githubusercontent.com/27302986/191944841-4caf6c35-7395-4329-8203-6ef68ff352a6.mp4

```
"react": "18.2.0",
"react-native": "0.71.0",
---
"@react-navigation/native": "6.1.2",
"@react-navigation/native-stack": "6.9.8",
"react-native-gesture-handler": "2.9.0",
"react-native-safe-area-context": "4.4.1"
"react-native-screens": "3.18.2"

<GestureHandlerRootView style={{ flex: 1 }}>
	<NavigationContainer>
		<Stack.Navigator
		screenOptions={{
			headerMode: "screen"
		}}
		initialRouteName="Home">
		<Stack.Screen name="Home" component={Home} />
		<Stack.Screen
			name="Page"
			component={Page}
			options={{ animation: "slide_from_right" }}
		/>
		</Stack.Navigator>
	</NavigationContainer>
</GestureHandlerRootView>

props.navigation.navigate("Page");
props.navigation.goBack();
```

### Steps to reproduce

1. I go to a page.
2. I click the back button.
3. **Everything disappears. A white page appears instantly** and the previous page opens.

### Snack or a link to a repository

https://stackoverflow.com/help/mcve

### Screens version

3.18.2

### React Native version

0.71.0

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

_No response_

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by alduzy**
## Description

This PR intents to fix current screen going blank on Android when returning to the previous one. The issue has been already fixed by https://github.com/software-mansion/react-native-screens/pull/2134, but re-appeared recently. After a quick bisect it turned out that https://github.com/software-mansion/react-native-screens/pull/2412 caused the regression. Bringing back the removed `NativeScreensModule` export fixes the issue.

Fixes #1685 

## Changes

- added missing export
- modified `Test2282.tsx` repro

### Before

https://github.com/user-attachments/assets/39bf6c66-39d2-4dfd-abc8-ee1c690417a4

### After

https://github.com/user-attachments/assets/003446b2-c976-4cdb-8ab4-348dd619ba79

## Test code and steps to reproduce

- use `Test2282.tsx` repro

## Checklist

- [x] Included code example that can be used to test this change
- [x] Ensured that CI passes

### CODE REVIEW

File: src/index.tsx [hunk 1]
```diff
@@ -37,6 +37,11 @@ export { default as FullWindowOverlay } from './components/FullWindowOverlay';
 export { default as ScreenFooter } from './components/ScreenFooter';
 export { default as ScreenContentWrapper } from './components/ScreenContentWrapper';
 
+/**
+ * Modules
+ */
+export { default as NativeScreensModule } from './fabric/NativeScreensModule';
```
Comment (kkafar) [inline src/index.tsx:43]:
```suggestion
export { default as NativeScreensModule_INTERNAL_DO_NOT_USE } from './fabric/NativeScreensModule';
```

**Review by kkafar — CHANGES_REQUESTED** [review]
It just came to my mind that we could do following 👇🏻 just temporarily, before we complete screen transition API migration by @maciekstosio.

I would be even fine to leave it this way. Its ugly - true, but it achieves all I want:

1. We ensure the turbomodule is loaded
2. We'll be able to remove it from public interface at any point w/o breaking change.

**Review by kkafar — APPROVED** [review]
Yeah, I think we're good now
