### PR TITLE
fix: Remove interaction disabling code for modals

### LINKED ISSUE #3480: iOS modal/formSheet: keyboard re-opens after screen focus when it was open in the previous screen
### Description

When opening a modal while a TextInput is focused, the keyboard closes, but then re-opens after the modal opens. 

See this video made by adding a basic TextInput in FabricExample, bug is visible the second time I open the formSheet, after I focused the keyboard.

https://github.com/user-attachments/assets/ae6e1188-6153-4937-bd56-3dd71397138a

### Steps to reproduce

1. Add a TextInput to the example app in `apps/src/tests/TestFormSheet.tsx` >  `Home`
2. Focus it
3. Open a formSheet with one of the button

Repro conditions I confirmed:

- iOS 26.1 or 26.2,
- build with Xcode 26.1.1
- react-native-screens 4.18.0 or from main today

### Snack or a link to a repository

https://github.com/matthieugicquel/react-native-screens/tree/repro-wild-keyboard-appears

### Screens version

3.18.0 and up

### React Native version

0.81.5 and 0.83.0-rc.4

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

iPhone 16 Pro

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by kmichalikk**
Fixes #3480 

This PR removes the code that was used to disable interactions for the time when multiple modals could be dismissed. It tried to find a minimal subroot similar to Stack Screen, but in doing so, it used reactSuperview, which pointed to the Stack, not to the actual view in its parent chain, resulting in disabling the interactions for unrelated part of the app, which in turn caused the bug with reopening the keyboard when some TextView was focused on the Stack Screen.

## Changes

Removed the `presentationControllerWillDismiss` callback.

## Before & after - visual documentation

| Before | After |
| --- | --- |
| <video src="https://github.com/user-attachments/assets/39e70947-efc7-4aee-a851-6b606921282d" /> | <video src="https://github.com/user-attachments/assets/a4f18229-14c7-4f1f-8b18-f732a396bab5" /> |

## Test plan

Use Test3480, Test3093 and Modals example to verify Stack and Modals.

## Checklist

- [x] For visual changes, included screenshots / GIFs / recordings documenting the change.
- [x] Ensured that CI passes

### CODE REVIEW

**Review by kligarski — APPROVED** [review]

**Review by kkafar — APPROVED** [review]
Looks reasonable, thank you.

File: ios/RNSScreen.mm [hunk 1]
```diff
@@ -818,15 +818,9 @@ - (void)willMoveToWindow:(UIWindow *)newWindow
...
     // starting from reactSuperview, because on Paper, self is not attached yet.
-    [RNSScreenView.viewInteractionManagerInstance disableInteractionsForSubtreeWith:self.reactSuperview];
-  }
-}
-
-- (void)presentationControllerWillDismiss:(UIPresentationController *)presentationController
-{
-  if (@available(iOS 26, *)) {
-    // Disable interactions to disallow multiple modals dismissed at once; see willMoveToWindow
-    [RNSScreenView.viewInteractionManagerInstance disableInteractionsForSubtreeWith:self.reactSuperview];
```
Comment (kkafar) [inline ios/RNSScreen.mm:829]: I think this function should not be removed completely. It has some more code over than the part you remove. I think the parenthesis were incorrectly matched. Please see to it.

**Review by kkafar — CHANGES_REQUESTED** [review]

File: ios/RNSScreen.mm (hunk 1 above)
Comment (kmichalikk) [reply ios/RNSScreen.mm:829]: [f57837e](https://github.com/software-mansion/react-native-screens/pull/3555/commits/f57837e30321b1ff3265b06a93d5b0f6049d818a)

**Comment by ferrannp** [comment]
@kmichalikk @kkafar this exact same bug exists on Android. Tested 4.20.0, 4.21.0 and 4.22.0, all them are broken.
