### PR TITLE
fix: issues with presenting owned modals from foreign ones

### LINKED ISSUE #2048: iOS: `Screen` with `{ presentation: "modal" }` navigated to from within another react-native's `Modal` doesn't open
### Description

https://github.com/software-mansion/react-native-screens/releases/tag/3.29.0 and https://github.com/software-mansion/react-native-screens/pull/1912 are causing breaking change in behaviour of `'@react-navigation/native-stack'`'s `Screen` that is mounted with `{ presentation: "modal" }`.

Hiding the `react-native`'s `Modal` that is the most top component in the view hierarchy prevents `Screen` with `{ presentation: "modal" }` from showing.
My scenario:
1. show a `BottomSheet` that is based on `react-native`'s `Modal` with an action button
2. clicking the button should hide the `BottomSheet` and navigate to `{ presentation: "modal" }` individual Screen

| Before `3.29.0` (`3.28.0` here) - desired behaviour | `3.29.0` - breaking change | `3.29.0` - without `BottomSheet` autohide |
|-|-|-|
| <video src=https://github.com/software-mansion/react-native-screens/assets/16623003/b3cf2994-e438-4f86-8bf4-f53f2970dd2d height=480 /> | <video src=https://github.com/software-mansion/react-native-screens/assets/16623003/18bbcf97-0c5e-4d87-b504-3bb1c53ce69a height=480 /> | <video src=https://github.com/software-mansion/react-native-screens/assets/16623003/91f38632-b3ed-4cea-84b2-aab61ac91e58 height=480 /> |

### Steps to reproduce

1. Open https://snack.expo.dev/@bbarthec/react-native-screens-modal-in-modal-issues
2. Open the snack in Expo GO (SDK 50 comes with version `3.29.0`) on either physical iPhone or Simulator
3. Open `BottomSheet` modal & open `Screen` modal - see `Screen` is not visible. It's probably mounted using dismissed `BottomSheet` modal as an anchor component.
4. Commend out `setVisible(false)` from line 51 and repeat the process. See the modal `Screen` properly mounts.

### Snack or a link to a repository

https://snack.expo.dev/@bbarthec/react-native-screens-modal-in-modal-issues

### Screens version

3.29.0

### React Native version

0.73

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

None

### Device model

_No response_

### Acknowledgements

Yes

### LINKED ISSUE #2085: Not able to navigate to a nested modal navigator
### Description

When trying to open a nested modal, the screen isn't opening. After some research this is due to the `__block` keyword.
This seems to be wrongly fixed in this PR: https://github.com/software-mansion/react-native-screens/commit/471127e26aa23eed4d14388a9646bf83de5e8699

Changing the following line will fix the issue:

```
  __block UIViewController *changeRootController = _controller;
```

into 

```
UIViewController *changeRootController = _controller;
```

### Steps to reproduce

1. Use Test1829 and open a nested modal

### Snack or a link to a repository

not-needed

### Screens version

3.30.1

### React Native version

0.72.x

### Platforms

iOS

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by kkafar**
## Description

Basically this is another edition of the issue #1829 (handled by #1912).
The issue comes down to the fact, that our `ScreenStack` is not aware of all modal view controllers being in presentation,
but this time it is not aware of third-party modal view controllers (I've named them "foreign" modals in opposite to "owned" modals).

This PR is not a comprehensive solution but rather just a patch aiming at fixing one particular interaction reported in #2048.

I've left verbose code comments explaining the issue and suggesting solution in the source code, including:

```
  // TODO: Find general way to manage owned and foreign modal view controllers and refactor this code. Consider building
  // model first (data structue, attempting to be aware of all modals in presentation and some text-like algorithm for
  // computing required operations).
```

Closes #2048
Closes #2085

## Changes

Trigger dissmisal of foreign modal if it is presented above `changeRoot` modal (last modal that is to stay on stack after the updates).

## Test code and steps to reproduce

`Test2048` in `TestsExample` & `FabricTestExample`.

## Checklist

- [x] Included code example that can be used to test this change
- [x] Ensured that CI passes

### CODE REVIEW

**Comment by kkafar** [comment]
TODO: Checkout whether I need to handle RNSModalScreenComponent (or whatever its name is)

File: ios/RNSScreenStack.mm [hunk 1]
```diff
@@ -382,9 +382,13 @@ - (void)setModalViewControllers:(NSArray<UIViewController *> *)controllers
   [newControllers removeObjectsInArray:_presentedModals];
 
   // We need to find bottom-most view controller that should stay on the stack
-  // for the duration of transition. There are couple of scenarios:
+  // for the duration of transition.
+  // We will want to dismiss all
```
Comment (tboba) [inline ios/RNSScreenStack.mm:386]: ...to dismiss all what? 😄

File: ios/RNSScreenStack.mm [hunk 2]
```diff
@@ -479,16 +483,35 @@ - (void)setModalViewControllers:(NSArray<UIViewController *> *)controllers
...
+  // batch of transitions. Therefore changeRootController.presentedViewController is the first constroller to be
+  // dismissed (implying also all controllers above). Notice here, that firstModalToBeDismissed could have been
+  // RNSScreen modal presented from *this* stack, another stack, or any other view controller with modal presentation
+  // provided by third-party libraries (e.g. React Native's Modal view). In case of presence of other (not managed by
+  // us) modal controllers, weird interactions might arise. The code below, besides handling our presentation /
+  // dismissal logic also attempts to handle possible wide gamut of cases of interactions with third-party modal
+  // controllers, however it's not perfect.
+  // TODO: Find general way to manage owned and foreign modal view controllers and refactor this code. Consider building
+  // model first (data structue, attempting to be aware of all modals in presentation and some text-like algorithm for
+  // computing required operations).
```
Comment (tboba) [inline ios/RNSScreenStack.mm:496]: Should we post a draft with this TODO on our agenda?

File: ios/RNSScreenStack.mm [hunk 3]
```diff
@@ -479,16 +483,35 @@ - (void)setModalViewControllers:(NSArray<UIViewController *> *)controllers
...
   UIViewController *firstModalToBeDismissed = changeRootController.presentedViewController;
+
   if (firstModalToBeDismissed != nil) {
     BOOL shouldAnimate = changeRootIndex == controllers.count &&
         [firstModalToBeDismissed isKindOfClass:[RNSScreen class]] &&
         ((RNSScreen *)firstModalToBeDismissed).screenView.stackAnimation != RNSScreenStackAnimationNone;
 
-    if ([_presentedModals containsObject:firstModalToBeDismissed]) {
+    if ([_presentedModals containsObject:firstModalToBeDismissed] ||
+        ![firstModalToBeDismissed isKindOfClass:RNSScreen.class]) {
```
Comment (tboba) [inline ios/RNSScreenStack.mm:506]: Let's stick to the convention here:

```suggestion
        ![firstModalToBeDismissed isKindOfClass:[RNSScreen class]]) {
```

File: ios/RNSScreenStack.mm [hunk 4]
```diff
@@ -382,9 +382,13 @@ - (void)setModalViewControllers:(NSArray<UIViewController *> *)controllers
   [newControllers removeObjectsInArray:_presentedModals];
 
   // We need to find bottom-most view controller that should stay on the stack
-  // for the duration of transition. There are couple of scenarios:
+  // for the duration of transition.
+  // We will want to dismiss all
+
+  // There are couple of scenarios:
   // (1) No modals are presented or all modals were presented by this RNSNavigationController,
   // (2) There are modals presented by other RNSNavigationControllers (nested/outer)
```
Comment (tboba) [inline ios/RNSScreenStack.mm:390]: Just a small nit: add `,` at the end of this line 😄 :sorrry:

**Review by tboba — APPROVED** [review]
On first sight, it looks good to me! Just left some small comments 🎉

File: ios/RNSScreenStack.mm (hunk 1 above)
Comment (kkafar) [reply ios/RNSScreenStack.mm]: +1, this is leftover from my side. I've decided to write that information in different place (somewhere below).

https://github.com/software-mansion/react-native-screens/pull/2113/commits/9e6f2f9f74f43c28b02f3a24d61616e1546cccc0

File: ios/RNSScreenStack.mm (hunk 4 above)
Comment (kkafar) [reply ios/RNSScreenStack.mm]: https://github.com/software-mansion/react-native-screens/pull/2113/commits/0e1b5e606ab81042ca2d4f90af95779132a2a5dd 😅

**Comment by kkafar** [comment]
Thanks for review. I'll wait with merging till I get response on #2048.

File: ios/RNSScreenStack.mm [hunk 5]
```diff
@@ -479,16 +482,35 @@ - (void)setModalViewControllers:(NSArray<UIViewController *> *)controllers
     }
   };
 
+  // changeRootController is the last controller that *is owned by this stack*, and should stay unchanged after this
+  // batch of transitions. Therefore changeRootController.presentedViewController is the first constroller to be
```
Comment (WoLewicki) [inline ios/RNSScreenStack.mm:486]: `controller`

File: ios/RNSScreenStack.mm [hunk 6]
```diff
@@ -479,16 +482,35 @@ - (void)setModalViewControllers:(NSArray<UIViewController *> *)controllers
...
+  // dismissed (implying also all controllers above). Notice here, that firstModalToBeDismissed could have been
+  // RNSScreen modal presented from *this* stack, another stack, or any other view controller with modal presentation
+  // provided by third-party libraries (e.g. React Native's Modal view). In case of presence of other (not managed by
+  // us) modal controllers, weird interactions might arise. The code below, besides handling our presentation /
+  // dismissal logic also attempts to handle possible wide gamut of cases of interactions with third-party modal
+  // controllers, however it's not perfect.
+  // TODO: Find general way to manage owned and foreign modal view controllers and refactor this code. Consider building
+  // model first (data structue, attempting to be aware of all modals in presentation and some text-like algorithm for
```
Comment (WoLewicki) [inline ios/RNSScreenStack.mm:494]: `structure`

File: ios/RNSScreenStack.mm [hunk 7]
```diff
@@ -479,16 +482,35 @@ - (void)setModalViewControllers:(NSArray<UIViewController *> *)controllers
...
         ((RNSScreen *)firstModalToBeDismissed).screenView.stackAnimation != RNSScreenStackAnimationNone;
 
-    if ([_presentedModals containsObject:firstModalToBeDismissed]) {
+    if ([_presentedModals containsObject:firstModalToBeDismissed] ||
+        ![firstModalToBeDismissed isKindOfClass:RNSScreen.class]) {
       // We dismiss every VC that was presented by changeRootController VC or its descendant.
       // After the series of dismissals is completed we run completion block in which
       // we present modals on top of changeRootController (which may be the this stack VC)
+      //
+      // There also might the second case, where the firstModalToBeDismissed is foreign.
```
Comment (WoLewicki) [inline ios/RNSScreenStack.mm:510]: `might be the second case`

**Review by WoLewicki — COMMENTED** [review]
Some spelling checks.

**Comment by WoLewicki** [comment]
Hopefully it did not destroy any scenarios where some code was aware of the problem and did its own workarounds for the issue. We should find a complete solution for the case ASAP I think.

**Comment by kkafar** [comment]
> Hopefully it did not destroy any scenarios where some code was aware of the problem and did its own workarounds for the issue.

Yeah, I can see it happen but 🤷🏻  In the end, we do not promise any stability of behaviour / API of native side code.

> We should find a complete solution for the case ASAP I think.

My idea revolves around implementing something in the shape of [Levenshtein distance algorithm](https://en.wikipedia.org/wiki/Levenshtein_distance), however it's problematic because at the level of screen stack we do not have accurate information about what modals are in presentation (there might be modals presented from other stack, or *foreign* modals*). Even if we computed this dynamically, e.g. by registering each presented modal in `RNSScreenStackManager`, which is shared between various `RNSScreenStack` instances, there arises issue of modals, that are not presented under separate `UITransitionView` 😅 How do we find such third-party modals? <-- this is open question for me. We can discuss this on some screens meeting.

I'll fix typos in follow up sometime soon

**Comment by hirbod** [comment]
I believe that this change or in general RNS causes problems on hot reload when another ViewController is present.
https://github.com/lodev09/react-native-true-sheet/issues/34

It works fine and detaches RNS Modals on reload (pressing R), but keeps the RNS Modal active when another UIViewController is on top of it.

**Comment by kkafar** [comment]
Hey @hirbod, would you mind opening a dedicated issue for the case you described? (🤞🏻 for reproduction). I'm sure we will be able to look into it.

**Comment by hirbod** [comment]
@kkafar I already found a solution

I patched `RNSScreenStack` and changed `invalidate`

```obj-c
- (void)invalidate {
    _invalidated = YES;
    [self dismissAllPresentedViewControllersFrom:_controller completion:^{
        // Ensure presented modals are removed and the controller is detached from its parent
        [_presentedModals removeAllObjects];
        [_controller willMoveToParentViewController:nil];
        [_controller removeFromParentViewController];
    }];
}

- (void)dismissOnReload {
    dispatch_async(dispatch_get_main_queue(), ^{
        [self invalidate];
    });
}

- (void)dismissAllPresentedViewControllersFrom:(UIViewController *)viewController completion:(void (^)(void))completion {
    if (viewController.presentedViewController) {
        [viewController.presentedViewController dismissViewControllerAnimated:NO completion:^{
            [self dismissAllPresentedViewControllersFrom:viewController completion:completion];
        }];
    } else {
        completion();
    }
}
```

**Comment by hirbod** [comment]
I'll open a PR

**Comment by kkafar** [comment]
Excellent, thank you!

**Comment by hirbod** [comment]
https://github.com/software-mansion/react-native-screens/pull/2175
