### PR TITLE
fix(iOS): forward scrollEdgeEffects to inner screen in modals (#3816)

### LINKED ISSUE #3816: scrollEdgeEffects has no effect on modal screen presentations (iOS/Fabric)
### Description

When using scrollEdgeEffects: { top: 'hidden', bottom: 'hidden' } as a screen option, it works correctly for push presentations but has no effect on modal presentations (formSheet, modal, fullScreenModal, pageSheet, etc.) on iOS with Fabric (New Architecture)

### Steps to reproduce

1. Create a native stack navigator with a modal screen
2. Add a ScrollView to the modal screen content
3. Set scrollEdgeEffects: { top: 'hidden', bottom: 'hidden' } on the screen options
4. Open the modal — scroll edge effects are still visible (Automatic), ignoring the hidden setting
5. Compare with a push screen using the same option — it works correctly

### Snack or a link to a repository

https://snack.expo.dev/@dernise/scrollview-edgeeffects

### Screens version

4.24.0

### React Native version

0.84.0

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Fabric (New Architecture)

### Build type

None

### Device

None

### Device model

_No response_

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by maxencehenneron**
## Description

When a modal has a header (`isHeaderInModal`), the content is wrapped in a nested `ScreenStack`/`Screen`. The `scrollEdgeEffects` prop was only set on the outer modal screen, which doesn't contain the scroll view. This forwards the prop to the inner screen where the scroll view actually lives.

Also adds `scrollEdgeEffect` props to `ModalScreenNativeComponent` codegen spec for the `headerShown: false` case, where the modal screen directly contains the scroll view.

Closes #3816.

## Changes

- Destructured `scrollEdgeEffects` in `ScreenStackItem.tsx` and forwarded it to the inner `<Screen>` when `isHeaderInModal` is true. The outer modal screen receives `undefined` since it has no scroll view.
- Added `bottomScrollEdgeEffect`, `leftScrollEdgeEffect`, `rightScrollEdgeEffect`, and `topScrollEdgeEffect` props to `ModalScreenNativeComponent.ts` codegen spec.

## Test plan

Test with `Test3816` in the apps example project.

1. Open the app and navigate to `Test3816`
2. Tap "Open formSheet modal"
3. Verify that scroll edge effects on the modal's scroll view match the configured values (`hidden` for all edges)
4. Compare with a modal using `headerShown: false` to verify that case also works

## Checklist

- [x] Included code example that can be used to test this change.
- [x] Updated / created local changelog entries in relevant test files.
- [ ] For visual changes, included screenshots / GIFs / recordings documenting the change.
- [x] For API changes, updated relevant public types.
- [ ] Ensured that CI passes

### CODE REVIEW

**Comment by maxencehenneron** [comment]
Ready to be reviewed.

IMG_4536
IMG_4535


Before/After: the scroll edge effects are correctly disabled.

**Comment by kligarski** [comment]
Hi, @maxencehenneron. Thank you for the PR - it looks good to me. I'll only push a small change to pass `undefined` to outer `Screen` when `isHeaderInModal` for clarity. After CI passes we'll be ready to merge.

File: src/components/ScreenStackItem.tsx [hunk 1]
```diff
@@ -177,6 +178,7 @@ function ScreenStackItem(
       hasLargeHeader={headerConfig?.largeTitle ?? false}
       sheetAllowedDetents={sheetAllowedDetents}
       style={[style, internalScreenStyle]}
+      scrollEdgeEffects={scrollEdgeEffects}
```
Comment (kligarski) [inline src/components/ScreenStackItem.tsx]:
```suggestion
      scrollEdgeEffects={isHeaderInModal ? undefined : scrollEdgeEffects}
```

Ok, I'm unable to push to your branch so I'll add a suggestion.
