### PR TITLE
fix: handle React Native loaded on Fragment

### LINKED ISSUE #1506: (Android - Crash): FragmentManager is already executing transactions
## Description
When react native screens are enabled on Android and the architecture is based on a single `Activity` plus React native is loaded in a Fragment, there's a crash when navigating and restoring the fragment state.

Having a single `Activity` app and using `Fragments` with navigation components as describe [here](https://developer.android.com/guide/navigation/navigation-getting-started) brings us to load React Native apps on a `Fragment`. We also want to enable React native screens, however, when enabled on Android, there's the following crash:
`    java.lang.RuntimeException: Unable to resume activity {com.swmansion.rnscreens.example/com.swmansion.rnscreens.example.MainActivity}: java.lang.IllegalStateException: FragmentManager is already executing transactions
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4445)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4477)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7697)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
     Caused by: java.lang.IllegalStateException: FragmentManager is already executing transactions
        at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:1686)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1716)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:323)
        at com.swmansion.rnscreens.ScreenContainer.removeMyFragments(ScreenContainer.kt:216)
        at com.swmansion.rnscreens.ScreenContainer.onDetachedFromWindow(ScreenContainer.kt:228)
        at android.view.View.dispatchDetachedFromWindow(View.java:20538)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3942)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3934)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3934)
        at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5560)
        at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5531)
        at android.view.ViewGroup.removeView(ViewGroup.java:5462)
        at androidx.fragment.app.FragmentContainerView.removeView(FragmentContainerView.kt:288)
        at androidx.fragment.app.SpecialEffectsController$Operation$State.applyState(SpecialEffectsController.java:470)
        at androidx.fragment.app.DefaultSpecialEffectsController.applyContainerChanges(DefaultSpecialEffectsController.java:822)
        at androidx.fragment.app.DefaultSpecialEffectsController$1.run(DefaultSpecialEffectsController.java:111)
        at androidx.fragment.app.SpecialEffectsController$Operation.complete(SpecialEffectsController.java:713)
        at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.java:770)
        at androidx.fragment.app.SpecialEffectsController$Operation.completeSpecialEffect(SpecialEffectsController.java:690)
        at androidx.fragment.app.DefaultSpecialEffectsController$SpecialEffectsInfo.completeSpecialEffect(DefaultSpecialEffectsController.java:855)
        at androidx.fragment.app.DefaultSpecialEffectsController.startAnimations(DefaultSpecialEffectsController.java:154)
        at androidx.fragment.app.DefaultSpecialEffectsController.executeOperations(DefaultSpecialEffectsController.java:123)
        at androidx.fragment.app.SpecialEffectsController.executePendingOperations(SpecialEffectsController.java:306)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1903)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1814)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1751)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:3177)
        at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:606)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
2022-07-03 22:00:08.008 30152-30152/com.swmansion.rnscreens.example E/AndroidRuntime:     at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1424)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2968)
        at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:2900)
        at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:285)
        at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:334)
        at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:323)
        at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:204)
        at android.app.Activity.performResume(Activity.java:8160)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4435)`

The reason of the crash seems to be:

- When setting up `ScreenContainer` it receives the `FragmentManager` from the Activity at some point.
- This same `FragmentManager` is used by the Navigation Components to navigate between fragments.
- When the `Fragment` that has react native tries to recover the state after a navigation, it tries to use the `Activity` `FragmentManager` which is already in use.

## Steps To Reproduce
To reproduce, I've recreated in the `Example` app a common use case: Load React native, put the app in the background and trigger a deep link. I've prepared the `Example` to do this so the steps are:

1. Launch the Example app
2. Tap Stack Presentation
3. Tap Form Sheet
4. Put some values in the form.
5. Background the app
6. Launch the following adb comand: `adb shell am start -W -a android.intent.action.VIEW -d "screens://screens" com.swmansion.rnscreens.example`

### Expected behavior
The react native screen should display without a crash

### Actual behavior
Crash with the above stack trace
## Reproduction
To reproduce the crash I've forked  `react-native-screens` github project and modified the example with the described architecture. The project can be found here: https://github.com/luislukas/react-native-screens

I reported this issue originally on https://github.com/software-mansion/react-native-screens/issues/819 but due to our architecture we had to disable `react-native-screens`. We would like to enable them now so any hint/help would be appreciated.

## Platform

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Architecture
I've forked the `react-native-screens` and added the Navigation Componentes plus `Fragments` architecture described aboved.

- [ ] Paper
- [ ] Fabric

## Workflow

- [ ] Managed workflow
- [ ] Bare workflow

## Package versions
I'm using a fork of this project just changing the Android project architecture.

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |         |
| @react-navigation/native               |         |
| @react-navigation/native-stack         |         |
| react-native-screens                   |         |
| react-native-safe-area-context         |         |
| react-native-gesture-handler           |         |
| react-native-reanimated                |         |
| expo                                   |         |

### PR DESCRIPTION
**Pull request by kkafar**
## Description

Fixes #1506 

`ScreenContainer#setupFragmentManager` method resolves `FragmentManager` instance for `ScreenContainer` to use for conducting transactions. Until now, when first (not nested) `ScreenContainer` was initialised we took `FragmentManager` from top level activity, but it leads to conflicts with native Android navigation when React Native is not loaded directly in main activity (there are cases (see #1506) when both `react-native-screens` & Android native navigation use simultaneously the same FragmentManager leading to crashes).

## Changes

Added a method resolving fragment manager whose fragment's view is `ReactRootView`.

## Test code and steps to reproduce

See #1506 for crash description and how to reproduce. 

## Checklist

- [ ] Included code example that can be used to test this change
- [ ] Ensured that CI passes

### CODE REVIEW

File: android/src/main/java/com/swmansion/rnscreens/ScreenContainer.kt [hunk 1]
```diff
@@ -135,6 +135,37 @@ open class ScreenContainer<T : ScreenFragment>(context: Context?) : ViewGroup(co
...
+        return if (context.supportFragmentManager.fragments.isEmpty()) {
+            // We are in standard React Native application w/o custom native navigation based on fragments.
+           context.supportFragmentManager
+        } else {
+            // We are in some custom setup & we want to use the closest fragment manager in hierarchy.
+            // `findFragment` method throws IllegalStateException when it fails to resolve appropriate
+            // fragment. It might happen when e.g. React Native is loaded directly in Activity
+            // but some custom fragments are still used. However such use case seems highly unlikely
+            // so, as for now, we let application crash.
+            FragmentManager.findFragment<Fragment>(rootView).childFragmentManager
```
Comment (kkafar) [inline android/src/main/java/com/swmansion/rnscreens/ScreenContainer.kt:165]: Potentially we could catch the exception here and fallback to `context.supportFragmentManager`:

```suggestion
            // We are in some custom setup & we want to use the closest fragment manager in hierarchy.
            // `findFragment` method throws IllegalStateException when it fails to resolve appropriate
            // fragment. It might happen when e.g. React Native is loaded directly in Activity
            // but some custom fragments are still used. However such use case seems highly unlikely
            // so, as for now, we let application crash.
            try { 
                FragmentManager.findFragment<Fragment>(rootView).childFragmentManager
            } catch (IllegalStateException e) {
                context.supportFragmentManager
            }
```

**Review by kkafar — COMMENTED** [review]
See the comment below

File: android/src/main/java/com/swmansion/rnscreens/ScreenContainer.kt (hunk 1 above)
Comment (kkafar) [reply android/src/main/java/com/swmansion/rnscreens/ScreenContainer.kt]: Change added with [714ddea](https://github.com/software-mansion/react-native-screens/pull/1553/commits/714ddea0dfafe421a5aacac42e23b165fe770afc)

**Comment by zhengjialu520** [comment]
There are still issues after making the changes
