### PR TITLE
fix(Android): going back on fabric with horizontal list crash

### LINKED ISSUE #2341: Android RN 0.75.3, app crashes when returning to the previous screen
### Description

When I return to the previous screen, the app crashes. I am using version RN 0.75.3. I have tested with other RN versions, and this issue occurs from version RN 0.75 onwards.

https://github.com/user-attachments/assets/97f32a60-3a97-4b37-af4e-388d4db08553

7a0f880c8e5c2802714d

### Steps to reproduce

app crashes when returning to the previous screen

### Snack or a link to a repository

https://github.com/Ngoca1k15PT/AppNew

### Screens version

3.34.0

### React Native version

0.75.3

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

Debug mode

### Device

Real device

### Device model

Xiaomi

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by alduzy**
## Description

This PR handles yet another case for going back on fabric. In the previous one (https://github.com/software-mansion/react-native-screens/pull/2383) I omitted a case where a horizontal list is simply rendered w/o being nested in any other list!

Fixes #2341 

## Changes

- updated `Test2292.tsx` repro
- handle `parentView is ReactHorizontalScrollView`

## Test code and steps to reproduce

- use `Test2282.tsx` repro

## Checklist

- [x] Included code example that can be used to test this change
- [x] Ensured that CI passes

### CODE REVIEW

File: android/src/main/java/com/swmansion/rnscreens/ext/ViewExt.kt [hunk 1]
```diff
@@ -40,6 +40,9 @@ internal fun View.isInsideScrollViewWithRemoveClippedSubviews(): Boolean {
     }
     var parentView = this.parent
     while (parentView is ViewGroup && parentView !is ScreenStack) {
+        if (parentView is ReactHorizontalScrollView) {
```
Comment (WoLewicki) [inline android/src/main/java/com/swmansion/rnscreens/ext/ViewExt.kt:43]: Maybe add it as `||` in the second if?

Comment (alduzy) [reply android/src/main/java/com/swmansion/rnscreens/ext/ViewExt.kt:43]: I tried it, but got a compilation error because of undeclared `removeClippedSubviews`. It seems like accessing specific properties is not possible when looking for multiple types with `is` in Kotlin

Comment (kkafar) [reply android/src/main/java/com/swmansion/rnscreens/ext/ViewExt.kt:43]: I see great usecase for `when` cause then

**Review by kkafar — COMMENTED** [review]
Just a single note, the logic seems ok.

File: android/src/main/java/com/swmansion/rnscreens/ext/ViewExt.kt (hunk 1 above)
Comment (alduzy) [reply android/src/main/java/com/swmansion/rnscreens/ext/ViewExt.kt]: https://github.com/software-mansion/react-native-screens/pull/2403/commits/1ccaa42fc7afc86496dfdd93347408246c145d17

**Review by kkafar — APPROVED** [review]
Final remark

File: android/src/main/java/com/swmansion/rnscreens/ext/ViewExt.kt [hunk 2]
```diff
@@ -40,8 +40,13 @@ internal fun View.isInsideScrollViewWithRemoveClippedSubviews(): Boolean {
...
-            return parentView.removeClippedSubviews
+        when (parentView) {
+            is ReactHorizontalScrollView -> {
+                return parentView.removeClippedSubviews
+            }
+            is ReactScrollView -> {
+                return parentView.removeClippedSubviews
+            }
         }
         parentView = parentView.parent
```
[the remark this answers is not in the document]
Comment (alduzy) [reply android/src/main/java/com/swmansion/rnscreens/ext/ViewExt.kt]: https://github.com/software-mansion/react-native-screens/pull/2403/commits/6ac7e07cc58f95438c8f9fa37811bddf479d564e
