### PR TITLE
fix: trigger color change on every update

### LINKED ISSUE #550: backButtonImage is not working on iPhone 11 Pro max & iPhone XS
Hello, Thanks for the good library.

backButtonImage works great. On iPhone 8, iPhone x.
However, on iPhone Xs and iPhone 11 (Pro, max), sometimes, problems occur.

```
"dependencies": {
    "@babel/plugin-proposal-decorators": "^7.8.3",
    "@react-native-community/async-storage": "^1.11.0",
    "@react-native-community/blur": "^3.6.0",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^5.9.2",
    "@react-native-community/viewpager": "^4.0.0",
    "@react-navigation/native": "^5.3.2",
    "@react-navigation/stack": "^5.3.2",
    "@types/lodash.debounce": "^4.0.6",
    "@types/react-native-share": "^3.3.0",
    "axios": "^0.19.2",
    "axios-retry": "^3.1.8",
    "date-fns": "^2.14.0",
    "lodash.debounce": "^4.0.8",
    "lottie-react-native": "^3.4.0",
    "mobx": "^5.15.4",
    "mobx-persist": "^0.4.1",
    "mobx-react": "^6.2.2",
    "react": "^16.9.0",
    "react-hook-form": "^5.7.2",
    "react-native": "0.62.2",
    "react-native-animatable": "^1.3.3",
    "react-native-code-push": "^6.2.1",
    "react-native-fast-image": "^8.1.5",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-get-random-values": "^1.4.0",
    "react-native-haptic-feedback": "^1.10.0",
    "react-native-in-app-message": "^1.0.31",
    "react-native-keychain": "^6.0.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-parallax-scroll-view": "^0.21.3",
    "react-native-push-notification": "^3.5.2",
    "react-native-reanimated": "^1.8.0",
    "react-native-router-flux": "^4.2.0",
    "react-native-safe-area-context": "^1.0.0",
    "react-native-screens": "^2.9.0",
    "react-native-shadow": "^1.2.2",
    "react-native-share": "^3.5.0",
    "react-native-splash-screen": "^3.2.0",
    "react-native-static-safe-area-insets": "^2.1.0",
    "react-native-svg": "^12.1.0",
    "react-native-swiper": "^1.6.0",
    "react-native-typography": "^1.4.1",
    "react-native-view-overflow": "^0.0.5",
    "react-native-webview": "^10.2.3",
    "react-navigation-collapsible": "^5.6.0",
    "react-string-replace": "^0.4.4",
    "react-uuid": "^1.0.2",
    "reanimated-bottom-sheet": "^1.0.0-alpha.20",
    "rn-placeholder": "^3.0.0",
    "styled-components": "^5.1.0",
    "uuid": "^8.1.0",
    "validatorjs": "^3.18.1"
  },
```

### PR DESCRIPTION
**Pull request by WoLewicki**
It is workaround for loading custom back icon when transitioning from a screen without header to the screen which has one. This action fails when navigating to the screen with header for the second time and loads default back button. It looks like changing the tint color of navbar triggers an update of the items belonging to it and it seems to load the custom back image so we change the tint color's alpha by a very small amount and then set it to the one it should have. Should resolve #550.

### CODE REVIEW

File: ios/RNSScreenStackHeaderConfig.m [hunk 1]
```diff
@@ -119,6 +119,8 @@ - (void)didUpdateReactSubviews
 + (void)setAnimatedConfig:(UIViewController *)vc withConfig:(RNSScreenStackHeaderConfig *)config
 {
   UINavigationBar *navbar = ((UINavigationController *)vc.parentViewController).navigationBar;
+  // really weird, but triggering the change of color resolves issue with custom back image, so we change it by a really small value and then back to the right one
+  [navbar setTintColor:[config.color colorWithAlphaComponent:CGColorGetAlpha(config.color.CGColor) - 0.01]];
```
Comment (Hirbod) [inline ios/RNSScreenStackHeaderConfig.m:123]: weird hack xD
