### PR TITLE
fix: Fixes header translucent change on iOS

### LINKED ISSUE #1158: Translucency isn't properly updated in tab navigator header
## Description

Translucency isn't properly updated in tab navigator header while changing tabs. Header's translucency is set when creating the header but it does not change when changing tabs. It changes only when we switch header to another one.

### Screenshots

https://user-images.githubusercontent.com/56412617/135244789-aedcad9a-951c-49cd-a339-9d9bf3d62ab7.mp4

## Steps To Reproduce

Bug is reproduced in sample app below.

1.  Create tab navigator nested in stack navigator.
2. Create two tabs, from which first's header should be translucent and second should not.
3. Try to switch tabs and see if header updates.
4. Push a new screen to stack navigator.
5. Go back to tab navigator and see if translucency settings changed.

### Expected behavior

Header transluency changes when switching tabs.

### Actual behavior

Header transluency does not change when switching tabs and it changes only when header is created or when header is switched e.g. from tab navigator header -> stack navigator header -> back to tab navigator header.

## Snack or minimal code example

[Repo with simple app created to show the bug](https://github.com/alicenoknow/TranslucentHeaderBug)

## Package versions

- React: 17.0.1
- React Native: 0.64.2
- React Native Screens: 2.16.1

### PR DESCRIPTION
**Pull request by Ubax**
## Description

Fixed #1158 

Before:

https://user-images.githubusercontent.com/32908614/135449788-3cc1e3cf-4672-4b83-b07e-fba872bb6a77.mov

After:

https://user-images.githubusercontent.com/32908614/135449747-473cc99b-c6d3-4695-b13f-98573fdfc58f.mov

## Checklist

- [x] Included code example that can be used to test this change
- [ ] Ensured that CI passes

### CODE REVIEW

File: ios/RNSScreenStackHeaderConfig.m [hunk 1]
```diff
@@ -138,10 +138,21 @@ - (void)updateViewControllerIfNeeded
   }
 }
 
+- (void)layoutNavigtationController
+{
+  UIViewController *vc = _screenView.controller;
+  UINavigationController *navctr = (UINavigationController *)vc.parentViewController;
+  [navctr.view setNeedsLayout];
+  [navctr.view layoutIfNeeded];
```
Comment (kacperkapusciak) [inline ios/RNSScreenStackHeaderConfig.m:146]:
```suggestion

```
It looks like this line is redundant

File: ios/RNSScreenStackHeaderConfig.m [hunk 2]
```diff
@@ -138,10 +138,21 @@ - (void)updateViewControllerIfNeeded
   }
 }
 
+- (void)layoutNavigtationController
```
Comment (kacperkapusciak) [inline ios/RNSScreenStackHeaderConfig.m:141]: This name doesn't reflect what this method does, also a typo 🙊

File: ios/RNSScreenStackHeaderConfig.m [hunk 3]
```diff
@@ -138,10 +138,21 @@ - (void)updateViewControllerIfNeeded
...
+  UINavigationController *navctr = (UINavigationController *)vc.parentViewController;
+  [navctr.view setNeedsLayout];
+  [navctr.view layoutIfNeeded];
+}
+
 - (void)didSetProps:(NSArray<NSString *> *)changedProps
 {
   [super didSetProps:changedProps];
   [self updateViewControllerIfNeeded];
+  if ([changedProps containsObject:@"translucent"]) {
```
Comment (kacperkapusciak) [inline ios/RNSScreenStackHeaderConfig.m:153]: This feels kinda hacky and it's wishful thinking that we won't add anything new with "translucent" in the name to unnecessarily redraw the hierarchy.

Comment (kacperkapusciak) [inline ios/RNSScreenStackHeaderConfig.m:153]: Please add a comment explaining this part with issue number

File: ios/RNSScreenStackHeaderConfig.m (hunk 2 above)
Comment (Ubax) [reply ios/RNSScreenStackHeaderConfig.m]: I added View to the name of the function

File: ios/RNSScreenStackHeaderConfig.m (hunk 1 above)
Comment (Ubax) [reply ios/RNSScreenStackHeaderConfig.m:146]: I am not sure when this will be called later. If in some cases it will not be called to late

File: ios/RNSScreenStackHeaderConfig.m (hunk 3 above)
Comment (Ubax) [reply ios/RNSScreenStackHeaderConfig.m:156]: 👍

File: ios/RNSScreenStackHeaderConfig.m (hunk 1 above)
Comment (Ubax) [reply ios/RNSScreenStackHeaderConfig.m:146]: 👍

File: ios/RNSScreenStackHeaderConfig.m [hunk 4]
```diff
@@ -138,10 +138,23 @@ - (void)updateViewControllerIfNeeded
   }
 }
 
+- (void)layoutNavigationControllerView
+{
+  UIViewController *vc = _screenView.controller;
+  UINavigationController *navctr = (UINavigationController *)vc.parentViewController;
```
Comment (WoLewicki) [inline ios/RNSScreenStackHeaderConfig.m:144]: Maybe we could just call `vc.navigationController`? If it gives the proper controller, we wouldn't need to cast it.

**Review by kacperkapusciak — APPROVED** [review]
LGTM

**Review by WoLewicki — APPROVED** [review]
