### PR TITLE
fix(iOS): add `canCoalesce` method to RNSHeaderHeightChangeEvent

### LINKED ISSUE #1932: RNSHeaderHeightChangeEvent: unrecognized selector sent to instance
### Description

With new architecture using stack navigator causes a crash, even the hello-react-navigation example is not working for me, if I let the Stack.Navigator component without any screens or a Stack.Screen outside a navigator I get errors but the app doesn't crash

[RNSHeaderHeightChangeEvent canCoalesce]: unrecognized selector sent to instance

image

System:
  OS: macOS 14.0
  CPU: (10) arm64 Apple M2 Pro
  Memory: 83.50 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.17.1
    path: ~/.nvm/versions/node/v18.17.1/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v18.17.1/bin/yarn
  npm:
    version: 9.6.7
    path: ~/.nvm/versions/node/v18.17.1/bin/npm
  Watchman:
    version: 2023.10.09.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/username/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - iOS 17.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 15.0/15A240d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 20.0.2
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/username/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.1
    wanted: 0.72.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: true

### Steps to reproduce

1. `NO_FLIPPER=1 USE_FRAMEWORKS=static RCT_NEW_ARCH_ENABLED=1 pod install`
2. `react-native start --reset-cache`
3. Build and run the app

### Snack or a link to a repository

https://snack.expo.dev/@joseluismurillorios/vigorous-blue-yogurt

### Screens version

3.26.0

### React Native version

0.72.1

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

_No response_

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by tboba**
## Description

It looks like when I was implementing class that is representing the `onHeaderHeightChange` I made a mistake and I forgot / accidentally removed `canCoalesce` method which led to displaying `RNSHeaderHeightChangeEvent: unrecognized selector sent to instance` for a couple of users.

This issue resolves that error by adding `canCoalesce` method to the event.
Fixes #1932.

## Changes

- Added `canCoalesce` method to `RNSHeaderHeightChangeEvent` file

## Test code and steps to reproduce

You can test the changes by checking `Test1802.tsx` component in FabricTestExample.

## Checklist

- [ ] Ensured that CI passes

### CODE REVIEW

File: ios/events/RNSHeaderHeightChangeEvent.mm [hunk 1]
```diff
@@ -31,6 +31,11 @@ - (NSDictionary *)body
   return body;
 }
 
+- (BOOL)canCoalesce
+{
+  return NO;
```
Comment (kkafar) [inline ios/events/RNSHeaderHeightChangeEvent.mm:36]: Actually don't we want this event to be coalesced? If we spam-emit the events from native to JS (e.g. when using scrollview & stretching large header) wouldn't it help improving performance a bit? 
I'm not familiar with event emitting internals & I'm not sure what are the conditions for the event instances to be coalesced, but it might be worth checking.

**Review by kkafar — COMMENTED** [review]
Just left a question

**Comment by kkafar** [comment]
Also please link the issue in the PR description.

Use "Closes/Fixes/..." syntax.

File: ios/events/RNSHeaderHeightChangeEvent.mm (hunk 1 above)
Comment (tboba) [reply ios/events/RNSHeaderHeightChangeEvent.mm:36]: You're right, I think we want this event to coalesce, but I'm afraid if there will be some issues with parsing double to `uint16_t` - I just wanted to make this change as safe as possible, but I can add coalescing key to this event 👍

Comment (kkafar) [reply ios/events/RNSHeaderHeightChangeEvent.mm:36]: Why do you need uint16? Coalescing key?

Comment (tboba) [reply ios/events/RNSHeaderHeightChangeEvent.mm]: Resolved in https://github.com/software-mansion/react-native-screens/pull/1933/commits/db7cd697d2336038b22c5d0bffafd5990369a7bc. Thanks!

One note from me about `coalesceWIthEvent` method - I believe both `coalescingKey` and `coalesceWithEvent` methods are required here, even if we're just returning `newEvent` from argument.

image

**Review by kkafar — APPROVED** [review]
LGTM
