### PR TITLE
fix(Fabric): back gesture activates `Pressable` elements

### LINKED ISSUE #2118: [iOS] back gesture activates `Pressable` element
### Description

If your `Pressable` "touches" the border of the screen and you do a back gesture on iOS, then after finger releasing this Pressable will be activated.

A difference between `native-stack` and `stack`:

|Stack|Native-Stack|
|------|-------------|
|<video src="https://github.com/software-mansion/react-native-screens/assets/22820318/f513096d-2744-4457-8cc6-5452c5ee788c">|<video src="https://github.com/software-mansion/react-native-screens/assets/22820318/4ab7b347-5772-451a-a23b-51774b3d6961">|

The issue can be reproducible in RNS example app, so I'm just posting a code sample instead of providing a full reproduction repo (let me know if it's not sufficient - I'll post full reproduction example then).

```tsx
import React, { useEffect } from 'react';
import {View, Text, Button, Pressable, StyleSheet, Alert} from 'react-native';
import {GestureHandlerRootView} from 'react-native-gesture-handler';

const fill = {flex: 1};

import { NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { createStackNavigator } from '@react-navigation/stack';
import BootSplash from '@libs/BootSplash';

function HomeScreen({navigation}) {
    useEffect(() => {
        BootSplash.hide();
    }, []);

    return (
        <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
            <Text>Home Screen</Text>
            <Button
                title="Go to Details"
                onPress={() => navigation.navigate('DetailsStack')}
            />
        </View>
    );
}

const styles = StyleSheet.create({
    wrapperCustom: {
        width: "100%",
        height: 100,
        marginHorizontal: 30,
        borderRadius: 10,
        margin: 10,
    },
    text: {
        fontSize: 20,
        color: 'black',
    },
});

function DetailsScreen({ navigation }) {
    return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
        {new Array(10).fill(0).map((_, i) => (
          <Pressable
            onPress={() => {
                Alert.alert('Pressed!');
            }}
            style={({pressed}) => [
                {
                backgroundColor: pressed ? 'rgb(210, 230, 255)' : 'white',
                },
                styles.wrapperCustom,
            ]}>
            {({pressed}) => (
                <Text style={styles.text}>{pressed ? 'Pressed!' : 'Press Me'}</Text>
            )}
            </Pressable>
        ))}
      </View>
    );
  }

const Stack = createNativeStackNavigator(); // <-- change to createStackNavigator to see a difference

function App() {
    return (
        <GestureHandlerRootView style={fill}>
            <NavigationContainer>
                <Stack.Navigator screenOptions={{animation: 'slide_from_left'}}>
                    <Stack.Screen name="Home" component={HomeScreen} />
                    <Stack.Screen name="DetailsStack" component={DetailsScreen} />
                </Stack.Navigator>
            </NavigationContainer>
        </GestureHandlerRootView>
    );
}

export default App;
```

### Steps to reproduce

1. go to details screen
2. swipe from left
3. release a finger

## Expected result

Alert shouldn't be shown

## Actual result

Alert is shown

### Snack or a link to a repository

https://github.com/software-mansion/react-native-screens

### Screens version

3.31.0

### React Native version

0.73.4

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 15 Pro (iOS 17.4)

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by kkafar**
## Description

When cancelling touches we previously relied on `touchHandler` instance being exposed by some react managed view above us (screen stack) in the view hierarchy (on Paper it was `RCTRootContentView`). However this changed with some recent Fabric version and no view exposes such property any longer, despite the fact that touch handler is obviously still utilised by these views even on Fabric, but the field has been removed from public API.

Currently on Fabric (as of version `0.74.1`) `RCTSurfaceTouchHandler` is owned by instance of `RCTFabricSurface` owned by instance of `RCTSurfaceView` which we can expect to live above us in the view hierarchy (RN mounts it in the very beginning of application runtime).

To get access to the private touchHandler (which is a `UIGestureRecognizer`) we observe that it is attached to the `RCTSurfaceView` and thus it is retained in its `gestureRecognizer` array (native API).

> [!tip]
> We could potentially cache the instance of `RCTSurfaceView`, but for now I've come to a conclusion that this is an minor minor computation (there is only one gesture recognizer in the array & the parent lookup is O(log n) (I know this is not a balanced tree, but you know what I mean). However this is always an option for future.

> [!note]
> I thought of adding warning in case of `RCTSurfaceView` being not present above screen stack in view hierarchy but this might be the case with `modal` stack presentation.

Closes #2118

## Changes

* Added utility extensions on `RCTTouchHandler` & `RCTSurfaceTouchHandler` classes to make the code more expressive
* Splited `RNSScreenStackView.cancelTouchesInParent` implementation into two separate for Paper & Fabric
* In case of Fabric added lookup for `RCTSurfaceView` & got access to its touch handler.

## Test code and steps to reproduce

`Test2118`

See #2118 for issue description.

## Checklist

- [x] Included code example that can be used to test this change
- [x] Ensured that CI passes

### CODE REVIEW

File: FabricTestExample/src/Test654.js [hunk 1]
```diff
@@ -5,8 +5,6 @@ import { createNativeStackNavigator } from '@react-navigation/native-stack';
 
 const Stack = createNativeStackNavigator();
 
-I18nManager.forceRTL(true);
-
```
Comment (tboba) [inline FabricTestExample/src/Test654.js:9]: Revert that change and merge branch with main

File: FabricTestExample/src/Test831.tsx [hunk 2]
```diff
@@ -12,8 +12,6 @@ type Props = {
 
 const Stack = createNativeStackNavigator();
 
-I18nManager.forceRTL(true);
-
```
Comment (tboba) [inline FabricTestExample/src/Test831.tsx:16]: Same as above

File: TestsExample/App.js [hunk 3]
```diff
@@ -98,6 +98,7 @@ import Test1981 from './src/Test1981';
 import Test2008 from './src/Test2008';
 import Test2048 from './src/Test2048';
 import Test2069 from './src/Test2069';
+import Test2118 from './src/Test2118';
```
Comment (tboba) [inline TestsExample/App.js:101]: Do we need this test in paper tests, if it's only a problem with Fabric?

File: ios/RNSScreenStack.mm [hunk 4]
```diff
@@ -731,19 +735,43 @@ - (void)cancelTouchesInParent
...
-    RCTSurfaceTouchHandler *touchHandler = [parent performSelector:@selector(touchHandler)];
+  }
+
+  // This could be possible in modal context
+  if (parent == nil) {
+    return;
+  }
+
+  RCTSurfaceTouchHandler *touchHandler = nil;
+  // Experimentation shows that RCTSurfaceTouchHandler is the only gestureRecogniser registered here,
```
Comment (tboba) [inline ios/RNSScreenStack.mm:754]: A small nit 😄 

```suggestion
  // Experimentation shows that RCTSurfaceTouchHandler is the only gestureRecognizer registered here,
```

File: ios/utils/RCTSurfaceTouchHandler+RNSUtility.mm [hunk 5]
```diff
@@ -0,0 +1,14 @@
+#ifdef RCT_NEW_ARCH_ENABLED
+#import "RCTSurfaceTouchHandler+RNSUtility.h"
+
+@implementation RCTSurfaceTouchHandler (RNSUtility)
+
+- (void)rns_cancelTouches
+{
+  [self setEnabled:NO];
+  [self setEnabled:YES];
```
Comment (tboba) [inline ios/utils/RCTSurfaceTouchHandler+RNSUtility.mm:9]: I don't quite like it. Can't we call `touchesCancelled` or `touchesEnded` method to somehow cancel the touch in other way?

File: ios/utils/RCTTouchHandler+RNSUtility.mm [hunk 6]
```diff
@@ -0,0 +1,15 @@
+#ifndef RCT_NEW_ARCH_ENABLED
+#import "RCTTouchHandler+RNSUtility.h"
+
+@implementation RCTTouchHandler (RNSUtility)
+
+- (void)rns_cancelTouches
+{
+  [self setEnabled:NO];
+  [self setEnabled:YES];
```
Comment (tboba) [inline ios/utils/RCTTouchHandler+RNSUtility.mm:9]: Same as above

**Review by tboba — CHANGES_REQUESTED** [review]
Great change, thanks! Just left a few comments

File: ios/RNSScreenStack.mm [hunk 7]
```diff
@@ -731,19 +735,43 @@ - (void)cancelTouchesInParent
...
+  // so we should not be afraid of any performance hit here.
+  for (UIGestureRecognizer *recognizer in parent.gestureRecognizers) {
+    if ([recognizer isKindOfClass:RCTSurfaceTouchHandler.class]) {
+      touchHandler = static_cast<RCTSurfaceTouchHandler *>(recognizer);
+    }
+  }
+
+  [touchHandler rns_cancelTouches];
```
Comment (WoLewicki) [inline ios/RNSScreenStack.mm:762]: Is it the default way of naming the extension (or however it is called) ?

File: FabricTestExample/src/Test654.js (hunk 1 above)
Comment (kkafar) [reply FabricTestExample/src/Test654.js]: https://github.com/software-mansion/react-native-screens/pull/2131/commits/1786094ba9e5195ecef8a693cbaa759eaa6d8ce5

File: FabricTestExample/src/Test831.tsx (hunk 2 above)
Comment (kkafar) [reply FabricTestExample/src/Test831.tsx]: https://github.com/software-mansion/react-native-screens/pull/2131/commits/1786094ba9e5195ecef8a693cbaa759eaa6d8ce5

File: TestsExample/App.js (hunk 3 above)
Comment (kkafar) [reply TestsExample/App.js:101]: This will be handled here: https://github.com/software-mansion/react-native-screens/pull/2135

File: ios/RNSScreenStack.mm (hunk 4 above)
Comment (kkafar) [reply ios/RNSScreenStack.mm]: https://github.com/software-mansion/react-native-screens/pull/2131/commits/8da1a1bff3b337a0ee9f6bee41432ee977558a60

File: ios/utils/RCTSurfaceTouchHandler+RNSUtility.mm (hunk 5 above)
Comment (kkafar) [reply ios/utils/RCTSurfaceTouchHandler+RNSUtility.mm:9]: I think changing this code is out of the scope of this PR. I'm reusing already existing & **working** code present in `RNSScreenStack.mm` & this change is only a refactor to improve code readability.

File: ios/utils/RCTTouchHandler+RNSUtility.mm (hunk 6 above)
Comment (kkafar) [reply ios/utils/RCTTouchHandler+RNSUtility.mm:9]: I think changing this code is out of the scope of this PR. I'm reusing already existing & **working** code present in `RNSScreenStack.mm` & this change is only a refactor to improve code readability.

File: ios/RNSScreenStack.mm (hunk 7 above)
Comment (kkafar) [reply ios/RNSScreenStack.mm:762]: Yes it is, see Obj-C docs: [link](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/CustomizingExistingClasses/CustomizingExistingClasses.html) (section "Avoid Category Method Name Clashes")

File: ios/utils/RCTSurfaceTouchHandler+RNSUtility.mm (hunk 5 above)
Comment (kkafar) [reply ios/utils/RCTSurfaceTouchHandler+RNSUtility.mm:9]: Also it is worth mentioned that this is approach used in RN internals

**Review by tboba — APPROVED** [review]
ok then

File: ios/RNSScreenStack.mm (hunk 7 above)
Comment (WoLewicki) [reply ios/RNSScreenStack.mm:762]: I think I'd go with rnscreens_cancelTouches since many libs can have a prefix of `rns`. wdyt?

Comment (kkafar) [reply ios/RNSScreenStack.mm]: Makes sense for me. https://github.com/software-mansion/react-native-screens/pull/2131/commits/30cfc12bdb45107a140453dc33b27ab848a8fa9f
