### PR TITLE
Fix broken layout for header subviews in iOS

### LINKED ISSUE #528: Header right elements disappear on rotate
Hello,

I've noticed that any elements placed inside header right (both using navigation.setOptions and view the Stack.Screen options) show when the stack is initially shown, but then if the device is rotated they disappear until the view is next reloaded.

This is only happening when the stack is created using createNativeStackNavigator and not when using React Navigation's createStackNavigator.

Anyone else encountering this? Any help would be appreciated.

### PR DESCRIPTION
**Pull request by abram**
## Description

This addresses bugs such as #528 where header content is incorrectly positioned on initial load or after rotation. I was experiencing these issues in my current app, and when I looked at the XCode view debugger I could see that `RNSScreenStackHeaderConfig` subviews had their `.frame.origin.x` property set to a non-zero value that moved them out of place.

I'm fairly new to React Native and very new to this codebase, so I haven't totally got to the bottom of what's happening here. My guess/theory is that RN layout code is setting the position of these views as if they're part of of the regular view hierarchy, even though they're meant to be managed by a `UINavigationBar`. Rather than trying to fix this at a deeper level and risk introducing side effects, I've added a small workaround.

Fixes #528.

## Changes

This PR adds a few lines of code inside `RNSScreen.viewDidLayoutSubviews` which manually set the `.frame.origin.x` and `.y` of each  `RNSScreenStackHeaderConfig` to zero. I believe it's accomplishing the same thing as PR #668 (which was my starting point for this work) but in a simpler and more direct way.

### CODE REVIEW

**Comment by WoLewicki** [comment]
Thanks for the PR! Yeah looks like the layouts passed by yoga layout are somehow trying to apply their calculations instead of leaving the origin to 0. I will test it and let other users do it and if it works, I think we can merge it :tada:

**Comment by WoLewicki** [comment]
Maybe instead of changing it in `RNScreen.m`, we could do it directly in `RNSScreenStackHeaderSubview.m`. It would look something like this added here: https://github.com/software-mansion/react-native-screens/blob/master/ios/RNSScreenStackHeaderConfig.m#L43.

```objc
- (void)reactSetFrame:(CGRect)frame
{
  [self setFrame:CGRectMake(0, 0, frame.size.width, frame.size.height)];
}
```

Could you test it and if it works the same, maybe add it like this instead?

**Comment by abram** [comment]
Brilliant! That's definitely a better place for this change. I updated the PR as you suggested and the fix still works as it should, at least in my testing.

File: ios/RNSScreenStackHeaderConfig.m [hunk 1]
```diff
@@ -41,6 +41,13 @@ - (instancetype)initWithBridge:(RCTBridge *)bridge
   return self;
 }
 
+- (void) reactSetFrame:(CGRect)frame
+{
+  // Block any attempt to set coordinates a RNSScreenStackHeaderSubview. This
+  // allows the native UINavigationBar to control the position of header content.
```
Comment (WoLewicki) [inline ios/RNSScreenStackHeaderConfig.m:47]:
```suggestion
  // Block any attempt to set coordinates on RNSScreenStackHeaderSubview. This
  // makes UINavigationBar the only one to control the position of header content.
```

**Comment by hirbod** [comment]
@WoLewicki this is still happening randomly when I use headerRight. Sometimes, my buttons are totally off screen.

**Comment by WoLewicki** [comment]
@hirbod I haven't spotted this issue since this change iirc. Can you provide a repro where it can be spotted?

**Comment by hirbod** [comment]
It is nearly impossible to reproduce. 50 calls work, 1 does not. @WoLewicki

**Comment by WoLewicki** [comment]
Seems really weird since due to this PR it should be controlled by the native side and work just fine. I cannot say much without a repro unfortunately :/

**Comment by WoLewicki** [comment]
Does this code gets triggered when you navigate to a screen? Maybe there is some race condition between setting `headerRight` and the start of navigation animation, during which the system does not accept any layout changes on the header iirc. Does it happen anytime if you set `headerRight` in options of the stack's screen?

**Comment by hirbod** [comment]
Yes it gets triggered when I navigate to the screen. I did not encounter this when set directly in screens options, but I need dynamic function since I pass an onPress function there (toggling active state of my save button).

**Comment by WoLewicki** [comment]
Did you try using `useLayoutEffect` instead? I have no other idea how to solve it unfortunately if it is some kind of race condition between JS and native side.

**Comment by hirbod** [comment]
No I did not try `useLayoutEffect`, I could give it a try.
